### PR TITLE
Remove babel

### PR DESCRIPTION
**Pull request by davidbkemp**
An attempt at removing all the Babel stuff now that browsers and NodeJS mostly support "modern" Javascript.  The less tools and libraries I use, the less I have to worry about constantly upgrading the tools and libraries.

I am not convinced this is the way to go.  Using standard ES modules within Node is messy.  Wondering if I should instead go back to CommonJS modules and use some tool to generate an ES module.  But that would sort of defeat one of the reasons for going with standard ES.

### CODE REVIEW

**Comment by davidbkemp** [comment]
@tearsofphoenix and @kamakiri01
Each of you have either contributed or have in the past had a significant stake in jsqubits.  Before merging these changes, it would be good to know if you still have any interest in jsqubits and, if so, if you have any feedback on these changes.
 
I want to simplify the maintenance of jsqubits by reducing the third party tools and libraries that it relies on.

In particular, I wanted to remove the use of Babel so that the library could even be used without requiring a build step.

Modern browsers and recent versions of NodeJS all seem to support modern JavaScript and so I think it is OK to remove Babel.

I chose to stick with ES modules, but it does mean that users need to specify `"type": "module"` in their `package.json`.  I am now wondering if I should have switched back to "commonjs" modules.

@kamakiri01 I think the changes should still be compatible with your Type Script declarations.  At least I managed to get this to work after creating a `package.json` that included `"type": "module"`

Excuse my TypeScript... I have little experience with it.

```
import * as jsq from "jsqubits";
import QState = jsq.jsqubits.QState;

const {jsqubits} = jsq;
const {ALL} = jsqubits;

function deutsch(state: QState, f: (number) => number) {
    return state
        .hadamard(ALL)
        .applyFunction(1, 0, f)
        .hadamard(jsqubits.ALL)
        .measure(1).result;
}

function f(x: number): number {
    return (x + 1) % 2;
}

const initial: QState = jsqubits("|001>")
const result: number = deutsch(initial, f);

console.log(result);

```

**Comment by davidbkemp** [comment]
Unfortunately I struggled to get es-lint working without Babel. Will try to bring it back once it becomes compatible with ES modules.

**Comment by kamakiri01** [comment]
Thank you for mention. I am using jsqubits even now. It was good to see the changes before I merged this change.

I also checked the compatibility of declaration. Even in my local, jsqubits.d.ts can declare v2.0.0 of jsqubits.
There is no need to change jsqubits.d.ts code.
I think jsqubits users can continue to use TypeScript declarations by writing `"type": "module"` in their package.json.

One thing I've noticed is that some npm libraries don't seem to support ESModules yet. (e.g. Jest)
This means that users may struggled when using `"type": "module"`.
Therefore, I think users will either use workarounds or wait for library updates.
This is a case by case basis.

In jsqubits.d.ts, follow-up update for ESModules may wait for Jest to complete ESModules support.
(or temporarily skip the test).

I'm not against the decision to move to ESModules in jsqubits v2.0.0.
babel is a huge dependent. I think ESModules will become popular eventually.

**Comment by davidbkemp** [comment]
@kamakiri01 sadly Safari doesn't support static constants on a class.  I am keen for this code to work in recent versions of most browsers, and so I have moved the Complex constants ZERO, ONE, SQRT2, and SQRT1_2 into constants.js

We can always add them back if/when Safari supports static constants.

Unfortunately this might break your declarations for these constants:
https://github.com/qramana/jsqubits.d.ts/blob/master/types/jsqubits.d.ts#L191-L194

**Comment by kamakiri01** [comment]
```typescript
import * as q from "jsqubits";

console.log(q.jsqubits.ONE); // Complex { real: 1, imaginary: 0 }
console.log(q.jsqubits.Complex.ONE); // undefined
```

I've confirmed. jsqubits.d.ts for v2.0.0 will remove these constant declarations.

**Comment by davidbkemp** [comment]
It has just occurred to me that, as a convenience, we can copy those complex constants back onto `Complex` from within `index.js`.
A bit like the constants in `constants.js` are all copied onto `Qubits` here:
https://github.com/davidbkemp/jsqubits/blob/master/lib/index.js#L25

I might do this in a new release: maybe 2.1.0

**Pull request merged**
